services:
  backend:
    command:
      - /home/frappe/frappe-bench/env/bin/gunicorn
      - --chdir=/home/frappe/frappe-bench/sites
      - --bind=0.0.0.0:8000
      - --threads=4
      - --workers=2
      - --worker-class=gthread
      - --worker-tmp-dir=/dev/shm
      - --timeout=120
      - --preload
      - frappe.app:application

  scheduler:
    command: bench --site ${FRAPPE_SITE_NAME_HEADER:-erpnext.localhost} schedule

  frontend:
    ports:
      - ${HTTP_PUBLISH_PORT:-8080}:8080
